INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Clean Up', 'Environment', 500, "5/30/21", "6/11/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Eat Up', 'Food', 1000, "5/30/21", "6/11/21");  
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Toys for Tots', 'Children', 1500, '5/30/21', '6/11/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Meals for the Hungry', 'Food', 400, '5/30/21', '6/11/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Wigs', 'Cancer', 500, '6/30/21', '7/4/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Best Pets', 'Animals', 1200, '6/30/21', '7/4/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Musical Sounds', 'Music', 700, '6/30/21', '7/4/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Autism Awareness', 'Autism', 800, '6/30/21', '7/4/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('PTSD Awareness', 'Military', 1000, '6/30/21', '7/4/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Doggie Days', 'Animals', 900, '6/30/21', '7/4/21');

INSERT INTO users (name, age) VALUES ("Pearce Rhead", 26);
INSERT INTO users (name, age) VALUES ("Jerry Rhead", 40);
INSERT INTO users (name, age) VALUES ("Heather Rhead", 50);
INSERT INTO users (name, age) VALUES ("Kim Rhead", 60);
INSERT INTO users (name, age) VALUES ("Illiana Gonzalez", 18);
INSERT INTO users (name, age) VALUES ("Tim Glew", 26);
INSERT INTO users (name, age) VALUES ("Noah White", 25);
INSERT INTO users (name, age) VALUES ("Colin Emerson", 28);
INSERT INTO users (name, age) VALUES ("Joe Ambrose", 19);
INSERT INTO users (name, age) VALUES ("Cam Dotson", 22);
INSERT INTO users (name, age) VALUES ("Matt Moy", 47);
INSERT INTO users (name, age) VALUES ("Katie Brandel", 31);
INSERT INTO users (name, age) VALUES ("Maggie Johnson", 45);
INSERT INTO users (name, age) VALUES ("Will Ferrell", 28);
INSERT INTO users (name, age) VALUES ("Lee Gonzalez", 39);
INSERT INTO users (name, age) VALUES ("Dom Trevino", 45);
INSERT INTO users (name, age) VALUES ("Rose Imhoff", 21);
INSERT INTO users (name, age) VALUES ("Jessie Herbert", 55);
INSERT INTO users (name, age) VALUES ("Jack Fossum", 16);
INSERT INTO users (name, age) VALUES ("Alex Smith", 30);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);